### ISSUE TITLE
Add api load

### ISSUE THREAD

**Issue by cityiron** [dubbogo/dubbo-go-proxy#7] opened 2020-09-09 09:01 UTC
**What would you like to be added**:
Api config can load from e.g: api_config.yaml, or config center like nacos.

**Why is this needed**:
Gateway must can control api, so api config load from remote or local.

**Comment by DogBaoBao** [comment] 2020-09-09 12:05
@williamfeng323

**Comment by yqxu** [comment] 2020-09-14 08:57
@williamfeng323  TieChen told me you will define a metadata of Dubbo api . In my issue I need a metadata of http api also. I prefer we can have a talk about this.      dingding : km6rfl0

**Comment by oaoit** [comment] 2020-09-17 12:06
get

**Comment by DogBaoBao** [comment] 2020-09-18 13:08
Duplicate of #17

**Closed** 2020-11-18 01:59 UTC
Labels: enhancement, high
