### ISSUE TITLE
user can add customized filter

### ISSUE THREAD

**Issue by zhangshen023** [dubbogo/dubbo-go-proxy#51] opened 2020-11-13 10:00 UTC
**What would you like to be added**:
allowing user add their customized filter
**Why is this needed**:
works of filters embedded in dubbo-go-proxy may not satisfied.So,adding customized filter is useful very much

**Comment by cityiron** [comment] 2020-12-18 07:55
Duplicate of #9 , we use plugin to customized filter.

**Closed** 2020-12-18 07:58 UTC
